
library(data.table)
library(tidyverse)
library(here)
library(sf)
library(oceanmap)
library(rnaturalearth)
library(RColorBrewer)
library(gridExtra)
library(purrr)
library(broom)
library(directlabels)

# data and parameters 
lonrange <- c(-78, -60)
latrange <- c(34.5, 48)
hadisst.neus <- read_rds(here("processed-data","hadisst_neus.rds"))

# get outline of USA
usoutline <- rnaturalearth::ne_states("united states of america", returnclass = "sf") %>% 
  # st_union() %>% #just to combine all polygons into a large one
  st_sf()

# load in coastal data generated by coastline_length.R
smoothline <- st_read(here("processed-data","coastline.shp"))
coastdistdat <- read_rds(here("processed-data","coastdistdat.rds"))

# make dots along coastline 
coastdistrefs <- coastdistdat %>% 
  filter(seglength > 0,
         seglength < 100000) %>% # get rid of weird points
  mutate(coastdist = lengthfromhere/1000,
         coastdistround = round(coastdist, digits = -2), # round to nearest hundred 
         coastdistdiff = abs(coastdist-coastdistround)) %>% 
  group_by(coastdistround) %>% 
  filter(coastdistdiff == min(coastdistdiff),
         coastdistround <= 1400) %>% 
  ungroup() %>% 
  dplyr::select(x, y, coastdistround)

# make map of the Northeast US 
neusmap <- ggplot() + 
  geom_sf(data=usoutline, color="#999999") +
  geom_sf(data=smoothline, size=2, color="#0072B2") + 
  geom_point(data=coastdistrefs, aes(x=x, y=y), color="black") +
  geom_text(data=coastdistrefs, aes(x=x, y=y, label=coastdistround),hjust=0, nudge_x = 0.5, fontface="bold", size=3) +
  scale_x_continuous(limits = c(-78, -65), expand = c(0, 0)) +
  scale_y_continuous(limits = c(34, 48), expand = c(0, 0)) +
  theme_bw() +
  theme(legend.position = "none",
        text=element_text(family="sans",size=12,color="black"),
        legend.text = element_text(size=12),
        axis.text=element_text(family="sans",size=8,color="black"), 
        axis.title=element_blank(),
        plot.margin=margin(t = 5, r = 0, b = 15, l = 5, unit = "pt")) +
  NULL


# prep SST data 
hadisst.prep <- hadisst.neus %>% 
  group_by(year, y) %>% 
  mutate(
    lat.year.month.mean = mean(sst)
  ) %>% 
  ungroup() %>% 
  dplyr::select(year, y, lat.year.month.mean) %>% 
  distinct()

# make colored grid 
sstgrid <- ggplot() + 
  geom_raster(data=hadisst.prep, aes(x=year, y=y, fill=lat.year.month.mean)) + 
  scale_fill_gradientn(colors=c("blue3","darkturquoise", "gold", "orangered", "red3"), limits = c(7,22), breaks = c(seq(8, 22, 2)),
                       guide = guide_colourbar(nbin=100, draw.ulim = FALSE, draw.llim = FALSE)) + 
  scale_x_continuous(limits = c(1968, 2017), breaks=seq(1968, 2017, 4), expand = c(0, 0)) +
  scale_y_continuous(limits = c(35, 45.1), breaks=seq(35, 45, 1), expand = c(0, 0)) +
  labs(x="Year", y="Latitude") +
  theme_bw() +
  theme(text=element_text(family="sans",size=12,color="black"),
        legend.text = element_text(size=12),
        axis.text=element_text(family="sans",size=8,color="black"), 
        axis.text.x = element_text(angle = 90, hjust = 1), 
        axis.title=element_text(family="sans",size=12,color="black"),
        plot.margin=margin(t = 15, r = 5, b = 5, l = 5, unit = "pt")) + 
  guides(fill = guide_colourbar(barwidth = 0.75, barheight = 25, title="SST", reverse=TRUE)) +
  NULL

neusfig <- grid.arrange(neusmap, sstgrid, ncol=2)
ggsave(neusfig, filename=here("results","fig_region_map.png"),width=11, height=8, dpi=300, scale=0.75)
